version: '3'

services:
  backend:
    volumes:
      - static:/app/backend/eyeglassy/static
    env_file:
      - .env
    build:
      context: ./backend/eyeglassy/
    ports:
      - "8000:8000"
    entrypoint: ./entrypoint.sh

volumes:
  static:
