# Generated by Django 4.1.7 on 2023-05-17 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.CharField(blank=True, max_length=20, null=True)),
                ('brand', models.CharField(blank=True, max_length=20, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=20, null=True)),
                ('shape', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'glasses',
            },
        ),
    ]
