# Generated by Django 4.2 on 2023-05-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glasses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('glasses_id', models.IntegerField()),
                ('glass_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
