# Generated by Django 4.1.7 on 2023-05-14 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='glasses',
            old_name='glass_name',
            new_name='brand',
        ),
        migrations.AddField(
            model_name='glasses',
            name='image',
            field=models.ImageField(blank=True, max_length=20, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='glasses',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='glasses',
            name='path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='glasses',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glasses',
            name='shape',
            field=models.CharField(default='round', max_length=20),
        ),
    ]
