# Generated by Django 4.1.7 on 2023-05-15 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_glass_name_glasses_brand_glasses_image_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='glasses',
            table='glasses',
        ),
    ]
