# Generated by Django 4.1.7 on 2023-05-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_glasses_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='glasses',
            name='glasses_id',
        ),
        migrations.AlterField(
            model_name='glasses',
            name='shape',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
