# Generated by Django 4.1.7 on 2023-05-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_glasses_glasses_id_alter_glasses_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glasses',
            name='image',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='glasses',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
