# Generated by Django 4.1.7 on 2023-05-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_glasses_image_alter_glasses_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glasses',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
