# Generated by Django 4.2 on 2023-05-11 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nickname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=128)),
                ('face_shape', models.CharField(blank=True, max_length=20, null=True)),
                ('glasses', models.ManyToManyField(blank=True, related_name='users', to='product.glasses')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
